### ISSUE TITLE
M3U8工具类对于一些链接无法正常执行正则过滤

### ISSUE THREAD

**Issue by ghost** [FongMi/TV#329]
尊敬的作者，您好，

测试的是量子资源站 http://lzizy.net

测试的具体播放链接 url ：https://vip.lz-cdn11.com/20220619/8759_937d7620/index.m3u8?sign=7d62d6cd604fe6aaf5cc246f41e7de42

配置文件的 rules 是：
```json
"rules": [
    {"name": "量子", "hosts": ["vip.lz", "hd.lz", ".cdnlz"], "regex": ["19.52","18.666667"]}
  ],
```

M3U8.java 里面的代码去掉一行后，可正常执行过滤，去掉的那一行代码是：
```java
if (response.header(HttpHeaders.ACCEPT_RANGES) != null) return "";
```

不知道是否是站点故意返回响应头来阻止程序的正常执行流程。

希望您有空可以看看。

最后，感谢您花时间看这个 issue

**Comment by FongMi** [comment]
好的，我在看看，感謝反應。

**Comment by FongMi** [comment]
測起來沒看到 Accept-Ranges
{access-control-allow-headers=[DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type], access-control-allow-methods=[GET, POST, OPTIONS], access-control-allow-origin=[*], cache-control=[max-age=2592000], content-length=[96], content-range=[bytes 0-95/96], content-type=[application/vnd.apple.mpegurl], date=[Sat, 02 Mar 2024 10:02:06 GMT], etag=["64319dc7-60"], expires=[Mon, 01 Apr 2024 10:02:06 GMT], last-modified=[Sat, 08 Apr 2023 17:00:55 GMT], server=[openresty], x-cache=[HIT, policy, disk]}

**Comment by ghost** [comment]
我的配置文件里面用的是量子采集类资源
```json
{"key":"量子","name":"量子资源","type": 1,"api": "https://cj.lziapi.com/api.php/provide/vod/",
      "categories": ["动作片", "喜剧片", "科幻片", "恐怖片", "爱情片", "剧情片", "战争片", "记录片", "国产剧", "欧美剧", "香港剧", "韩国剧", "台湾剧", "日本剧", "海外剧", "泰国剧", "国产动漫", "日韩动漫", "欧美动漫", "港台动漫", "海外动漫", "大陆综艺", "港台综艺", "日韩综艺", "欧美综艺"]
    },
```

然后随便播放一个视频，如 《女人我最大》，就发现无法正常过滤广告。

（1）刚刚我用您打包的apk进行测试了一下，使用的apk是 https://github.com/FongMi/Release/blob/fongmi/apk/release/leanback-java-armeabi_v7a.apk
用的播放器是 ijk，无法正常走完正则过滤，如果是 exo 的话可以正常过滤。这个 apk 的 exo 播放器应该是您进行优化过的

（2）我之前用的是 https://github.com/FongMi/TV 的 release 分支，参考了 IjkUtil.java 的代码，对 ExoUtil.java 进行补全相关的代码，然后打包 apk 在手机上测试，这时候 exo 就会出现上面无法正常执行过滤的问题。

**Comment by FongMi** [comment]
測起來是 Accept-Ranges 隨機的，有時會有，有時不會有，我再看看怎處理。

**Comment by ghost** [comment]
好的，非常感谢🙏
